apiVersion: v1
kind: Pod
metadata:
  name: burstable-pod
  labels:
    app: burstable-example
    tier: backend
spec:
  containers:
  - name: app-container
    image: nginx:1.21
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "200Mi"
        cpu: "500m"
    env:
    - name: QOS_CLASS
      value: "Burstable"
    - name: MIN_MEMORY
      value: "100Mi"
    - name: MAX_MEMORY
      value: "200Mi"
  restartPolicy: Always