apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi-container-example
    pattern: sidecar
spec:
  containers:
  - name: main-app
    image: nginx:1.21
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    env:
    - name: CONTAINER_ROLE
      value: "main"
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
  - name: log-collector
    image: busybox:1.35
    command: ['sh', '-c', 'while true; do tail -f /shared/access.log; sleep 10; done']
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"
    env:
    - name: CONTAINER_ROLE
      value: "sidecar"
    volumeMounts:
    - name: shared-logs
      mountPath: /shared
  - name: monitoring-agent
    image: busybox:1.35
    command: ['sh', '-c', 'while true; do echo "Monitoring metrics..."; sleep 30; done']
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    env:
    - name: CONTAINER_ROLE
      value: "monitoring"
  volumes:
  - name: shared-logs
    emptyDir: {}
  restartPolicy: Always