apiVersion: v1
kind: Pod
metadata:
  name: node-selector-pod
  labels:
    app: node-selector-example
    scheduling: node-selector
spec:
  containers:
  - name: web-server
    image: nginx:1.21
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    env:
    - name: SCHEDULING_TYPE
      value: "node-selector"
  nodeSelector:
    disktype: ssd
    environment: production
  restartPolicy: Always