apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-pod
  labels:
    app: node-affinity-example
    scheduling: node-affinity
spec:
  containers:
  - name: api-server
    image: nginx:1.21
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    env:
    - name: SCHEDULING_TYPE
      value: "node-affinity"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
            - arm64
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
      - weight: 50
        preference:
          matchExpressions:
          - key: environment
            operator: In
            values:
            - production
  restartPolicy: Always