apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-pod
  labels:
    app: web-frontend
    tier: frontend
    scheduling: pod-affinity
spec:
  containers:
  - name: frontend
    image: nginx:1.21
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "300m"
    env:
    - name: SCHEDULING_TYPE
      value: "pod-affinity"
    - name: BACKEND_HOST
      value: "database-service"
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - database
        topologyKey: kubernetes.io/hostname
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - web-frontend
          topologyKey: kubernetes.io/hostname
  restartPolicy: Always