apiVersion: v1
kind: Pod
metadata:
  name: resource-intensive-pod
  labels:
    app: resource-test
    type: intensive
spec:
  containers:
  - name: cpu-intensive
    image: busybox:1.35
    command: ['sh', '-c', 'yes > /dev/null']
    resources:
      requests:
        memory: "4Gi"
        cpu: "2000m"
      limits:
        memory: "8Gi"
        cpu: "4000m"
    env:
    - name: WORKLOAD_TYPE
      value: "intensive"
  restartPolicy: Never