version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production
      - MESSAGE=Hello from Docker Compose!
      - PORT=8080
    volumes:
      - web-logs:/app/logs
    networks:
      - app-network
    depends_on:
      - redis
      - db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    networks:
      - app-network
    depends_on:
      - web

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    command: redis-server --appendonly yes

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

volumes:
  web-logs:
  redis-data:
  db-data:

networks:
  app-network:
    driver: bridge