apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-sa
  namespace: default
  labels:
    app: webapp
    environment: development
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secure-sa
  namespace: default
  labels:
    app: secure-app
    environment: production
automountServiceAccountToken: false  # 보안이 중요한 경우 비활성화