# 최소 권한 원칙을 적용한 보안 강화 RBAC 설정

# 1. 특정 리소스만 접근 가능한 Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: specific-resource-access
rules:
- apiGroups: [""]
  resources: ["pods"]
  resourceNames: ["webapp-pod", "api-pod"]  # 특정 Pod만 접근 허용
  verbs: ["get", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["app-config"]  # 특정 ConfigMap만 접근 허용
  verbs: ["get"]
---
# 2. 읽기 전용 ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: readonly-sa
  namespace: default
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: specific-resource-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: readonly-sa
  namespace: default
roleRef:
  kind: Role
  name: specific-resource-access
  apiGroup: rbac.authorization.k8s.io
---
# 3. 로그 조회 전용 Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: log-reader
rules:
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]  # 로그를 보기 위해서는 Pod 목록 조회 필요
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-reader-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: log-reader-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: log-reader-sa
  namespace: default
roleRef:
  kind: Role
  name: log-reader
  apiGroup: rbac.authorization.k8s.io
---
# 4. 모니터링 전용 ClusterRole (읽기 전용)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-readonly
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/metrics", "pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
# Secret은 제외 - 민감한 정보 접근 차단
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-sa
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-readonly-binding
subjects:
- kind: ServiceAccount
  name: monitoring-sa
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: monitoring-readonly
  apiGroup: rbac.authorization.k8s.io