apiVersion: v1
kind: Pod
metadata:
  name: complex-app
  labels:
    app: complex-app
spec:
  containers:
  - name: app
    image: nginx:alpine
    ports:
    - containerPort: 80
    
    # Startup Probe: 시작 시간을 위한 충분한 시간 확보
    startupProbe:
      httpGet:
        path: /startup
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30  # 5분 (10초 * 30회)
    
    # Liveness Probe: 컨테이너 생존성 확인
    livenessProbe:
      httpGet:
        path: /health
        port: 80
        httpHeaders:
        - name: Custom-Header
          value: Liveness-Check
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
    
    # Readiness Probe: 트래픽 준비 상태 확인
    readinessProbe:
      httpGet:
        path: /ready
        port: 80
        httpHeaders:
        - name: Custom-Header
          value: Readiness-Check
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      successThreshold: 1
      failureThreshold: 3
    
    # 앱 초기화 및 헬스체크 엔드포인트 생성
    command:
    - /bin/sh
    - -c
    - |
      # 초기화 시뮬레이션 (30초 대기)
      echo "Initializing application..."
      sleep 30
      
      # 헬스체크 엔드포인트 생성
      mkdir -p /usr/share/nginx/html
      echo "<!DOCTYPE html><html><body><h1>Startup Complete</h1></body></html>" > /usr/share/nginx/html/startup
      echo "<!DOCTYPE html><html><body><h1>App is Healthy</h1></body></html>" > /usr/share/nginx/html/health
      echo "<!DOCTYPE html><html><body><h1>App is Ready</h1></body></html>" > /usr/share/nginx/html/ready
      echo "<!DOCTYPE html><html><body><h1>Complex App Running</h1></body></html>" > /usr/share/nginx/html/index.html
      
      # nginx 시작
      nginx -g 'daemon off;'