apiVersion: v1
kind: Pod
metadata:
  name: database-app
  labels:
    app: database-app
spec:
  containers:
  - name: postgres
    image: postgres:13-alpine
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_DB
      value: "testdb"
    - name: POSTGRES_USER
      value: "testuser"
    - name: POSTGRES_PASSWORD
      value: "testpass"
    
    # 시작 시간이 오래 걸리는 데이터베이스를 위한 Startup Probe
    startupProbe:
      tcpSocket:
        port: 5432
      initialDelaySeconds: 30
      periodSeconds: 10
      failureThreshold: 12  # 2분 대기 (10초 * 12회)
    
    # TCP 연결 확인용 Liveness Probe
    livenessProbe:
      tcpSocket:
        port: 5432
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
    
    # pg_isready로 실제 DB 준비 상태 확인하는 Readiness Probe
    readinessProbe:
      exec:
        command:
        - pg_isready
        - -h
        - localhost
        - -U
        - testuser
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3