apiVersion: v1
kind: Pod
metadata:
  name: exec-probe-app
  labels:
    app: exec-probe-app
spec:
  containers:
  - name: app
    image: busybox:latest
    
    # Exec Command Probe 예시
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3
    
    readinessProbe:
      exec:
        command:
        - test
        - -f
        - /tmp/ready
      initialDelaySeconds: 3
      periodSeconds: 3
      timeoutSeconds: 2
      failureThreshold: 3
    
    # 앱 시뮬레이션: 헬스체크 파일 생성 후 대기
    command:
    - /bin/sh
    - -c
    - |
      echo "Creating health check files..."
      touch /tmp/healthy
      touch /tmp/ready
      echo "Health check files created"
      
      # 앱 실행 시뮬레이션
      while true; do
        echo "App is running..."
        sleep 60
      done