apiVersion: v1
kind: Pod
metadata:
  name: tcp-probe-app
  labels:
    app: tcp-probe-app
spec:
  containers:
  - name: redis
    image: redis:alpine
    ports:
    - containerPort: 6379
    
    # TCP Socket Probe 예시
    livenessProbe:
      tcpSocket:
        port: 6379
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 3
    
    readinessProbe:
      tcpSocket:
        port: 6379
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3