apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: webapp-service
spec:
  selector:
    app: webapp-readiness
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP