apiVersion: v1
kind: Pod
metadata:
  name: app-pod-with-secret
  labels:
    app: secret-demo
spec:
  containers:
  - name: web-app
    image: nginx:latest
    ports:
    - containerPort: 80
    
    # 개별 환경변수로 Secret 사용
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: password
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: api-key
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: database-url
    
    # Secret의 모든 키를 환경변수로 가져오기
    envFrom:
    - secretRef:
        name: app-secret-v2
        optional: false
    
    # 리소스 제한
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  
  restartPolicy: Always
