# loadbalancer-service.yaml
# LoadBalancer 타입 서비스 (클라우드 로드밸런서)
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
  labels:
    app: nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  # 클라우드 제공업체별 설정이 다를 수 있음