apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce
  labels:
    project: ecommerce
    environment: production
    week: "2"
    day: "6"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ecommerce-quota
  namespace: ecommerce
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8" 
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    configmaps: "10"
    secrets: "10"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ecommerce-pdb
  namespace: ecommerce
spec:
  minAvailable: 1
  selector:
    matchLabels:
      tier: backend